@url=http://localhost:3000

### 0. RUTA DE PRUEBA (GET /)
GET {{url}}/api/auth

### 1. REGISTRAR NUEVO USUARIO (POST /register)
POST {{url}}/api/auth/register
Content-Type: application/json

{
    "nombre": "Conductor Prueba",
    "email": "prueba.nuevo@test.com",
    "contraseña": "miContraseñaSegura123"
}

### 2. INICIAR SESIÓN (POST /login)
# Usa el email y la contraseña que acabas de registrar
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "prueba.nuevo@test.com",
    "contraseña": "miContraseñaSegura123"
}
